-- My Plan Control Center Contract v1
-- Supabase/PostgreSQL. Run after enabling pgcrypto (gen_random_uuid).
create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id uuid primary key,
  local_user_id text unique,
  email text,
  display_name text,
  status text not null default 'active' check (status in ('active','disabled','banned')),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  app_version text,
  android_version text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.devices (
  installation_id text primary key,
  user_id uuid references public.app_users(id) on delete set null,
  device_name text,
  manufacturer text,
  model text,
  android_version text,
  app_version text,
  platform text not null default 'android',
  fcm_token text,
  status text not null default 'active' check (status in ('active','revoked','blocked')),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.premium_grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.app_users(id) on delete cascade,
  installation_id text references public.devices(installation_id) on delete set null,
  status text not null default 'active' check (status in ('active','revoked','expired')),
  grant_type text not null default 'manual' check (grant_type in ('manual','trial','subscription','promo','developer')),
  source text not null default 'control_center',
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  feature_keys jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.remote_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  value_type text not null default 'json' check (value_type in ('string','number','boolean','json')),
  description text,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.feature_flags (
  feature_key text primary key,
  enabled boolean not null default false,
  description text,
  audience_type text not null default 'all',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.app_versions (
  id uuid primary key default gen_random_uuid(),
  version_name text not null,
  version_code integer not null,
  apk_url text not null,
  release_notes text,
  release_date timestamptz not null default now(),
  minimum_version_code integer not null default 1,
  force_update boolean not null default false,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.remote_messages (
  id bigint generated by default as identity primary key,
  message_type text not null check (message_type in ('in_app','announcement','push','maintenance','update','warning')),
  title text not null,
  body text not null,
  image_url text,
  icon text,
  primary_button_text text,
  primary_action text default 'CLOSE',
  primary_url text,
  secondary_button_text text,
  secondary_action text default 'NONE',
  secondary_url text,
  target_type text not null default 'all' check (target_type in ('all','free','premium','user','group','device','version','android')),
  target_id text,
  target_value text,
  priority integer not null default 0,
  starts_at timestamptz,
  expires_at timestamptz,
  is_active boolean not null default true,
  dismissible boolean not null default true,
  frequency text not null default 'once' check (frequency in ('once','session','always','daily','until_action')),
  deep_link text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.message_receipts (
  message_id bigint not null references public.remote_messages(id) on delete cascade,
  installation_id text not null references public.devices(installation_id) on delete cascade,
  user_id uuid references public.app_users(id) on delete set null,
  delivered_at timestamptz,
  read_at timestamptz,
  dismissed_at timestamptz,
  primary key (message_id, installation_id)
);


-- Real two-way support conversations (separate from broadcast remote_messages).
create table if not exists public.support_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.app_users(id) on delete set null,
  installation_id text references public.devices(installation_id) on delete set null,
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.support_conversations(id) on delete cascade,
  sender_type text not null check (sender_type in ('user','admin')),
  sender_user_id uuid references public.app_users(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  read_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_support_conversations_user on public.support_conversations(user_id,updated_at desc);
create index if not exists idx_support_messages_conversation on public.support_messages(conversation_id,created_at asc);


create table if not exists public.notification_jobs (
  id uuid primary key default gen_random_uuid(),
  message_id uuid references public.remote_messages(id) on delete cascade,
  schedule_at timestamptz,
  sent_at timestamptz,
  status text not null default 'scheduled' check (status in ('scheduled','sending','sent','failed','cancelled')),
  target_type text not null default 'all',
  target_id text,
  target_value text,
  priority text not null default 'normal' check (priority in ('low','normal','high')),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.ad_settings (
  id boolean primary key default true,
  ads_enabled boolean not null default false,
  banner_enabled boolean not null default false,
  interstitial_enabled boolean not null default false,
  rewarded_enabled boolean not null default false,
  free_only boolean not null default true,
  frequency integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.maintenance_controls (
  id boolean primary key default true,
  enabled boolean not null default false,
  message text,
  starts_at timestamptz,
  ends_at timestamptz,
  allow_versions text[] not null default '{}',
  allow_admins boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.error_logs (
  id uuid primary key default gen_random_uuid(),
  category text,
  message text not null,
  stack_trace text,
  app_version text,
  android_version text,
  installation_id text,
  user_id uuid references public.app_users(id) on delete set null,
  occurrence_count integer not null default 1,
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  event_name text not null,
  user_id uuid references public.app_users(id) on delete set null,
  installation_id text,
  app_version text,
  android_version text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_activity_log (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid references auth.users(id),
  action text not null,
  target_type text,
  target_id text,
  old_state jsonb,
  new_state jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','support','developer')),
  permissions jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  content_type text not null check (content_type in ('news','study_tip','welcome','seasonal','premium_offer','help')),
  title text not null,
  body text not null,
  image_url text,
  action_label text,
  action_url text,
  audience_type text not null default 'all',
  audience_id text,
  starts_at timestamptz,
  expires_at timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.target_groups (
  id uuid primary key default gen_random_uuid(),
  group_key text unique not null,
  name text not null,
  description text,
  rules jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.target_group_members (
  group_id uuid not null references public.target_groups(id) on delete cascade,
  installation_id text not null references public.devices(installation_id) on delete cascade,
  user_id uuid references public.app_users(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (group_id, installation_id)
);

create table if not exists public.security_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','low','medium','high','critical')),
  installation_id text,
  user_id uuid references public.app_users(id) on delete set null,
  app_version text,
  android_version text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_devices_user on public.devices(user_id);
create index if not exists idx_devices_last_seen on public.devices(last_seen_at desc);
create index if not exists idx_premium_user_status on public.premium_grants(user_id,status);
create index if not exists idx_messages_active_window on public.remote_messages(is_active,starts_at,expires_at,priority desc);
create index if not exists idx_receipts_installation on public.message_receipts(installation_id);
create index if not exists idx_analytics_event_time on public.analytics_events(event_name,created_at desc);
create index if not exists idx_errors_time on public.error_logs(created_at desc);
create index if not exists idx_security_time on public.security_events(created_at desc);

-- Admin authorization helper. Control Center actions must use Supabase Auth + this table.
create or replace function public.cc_is_admin(required_role text default null)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.admins a
    where a.user_id = auth.uid() and a.enabled = true
      and (required_role is null or a.role in ('owner','admin',required_role))
  );
$$;

-- Secure admin RPCs. No service_role key belongs in the Android APK or browser.
create or replace function public.cc_grant_premium(
  p_user_id uuid, p_expires_at timestamptz, p_grant_type text default 'manual',
  p_source text default 'control_center', p_feature_keys jsonb default '[]'::jsonb, p_note text default null
) returns uuid language plpgsql security definer set search_path = public
as $$ declare v_id uuid;
begin
  if not public.cc_is_admin('admin') then raise exception 'not authorized'; end if;
  insert into public.premium_grants(user_id,status,grant_type,source,expires_at,feature_keys,note)
  values(p_user_id,'active',p_grant_type,p_source,p_expires_at,p_feature_keys,p_note) returning id into v_id;
  insert into public.admin_activity_log(admin_id,action,target_type,target_id,new_state)
  values(auth.uid(),'premium.grant','user',p_user_id::text,jsonb_build_object('grant_id',v_id,'expires_at',p_expires_at));
  return v_id;
end $$;

create or replace function public.cc_revoke_premium(p_grant_id uuid, p_reason text default null)
returns boolean language plpgsql security definer set search_path = public
as $$ begin
  if not public.cc_is_admin('admin') then raise exception 'not authorized'; end if;
  update public.premium_grants set status='revoked',updated_at=now(),note=coalesce(p_reason,note) where id=p_grant_id;
  return found;
end $$;

create or replace function public.cc_set_remote_config(p_key text,p_value jsonb,p_type text default 'json',p_description text default null,p_enabled boolean default true)
returns boolean language plpgsql security definer set search_path = public
as $$ begin
  if not public.cc_is_admin('admin') then raise exception 'not authorized'; end if;
  insert into public.remote_config(config_key,config_value,value_type,description,enabled,updated_by)
  values(p_key,p_value,p_type,p_description,p_enabled,auth.uid())
  on conflict(config_key) do update set config_value=excluded.config_value,value_type=excluded.value_type,description=excluded.description,enabled=excluded.enabled,updated_at=now(),updated_by=auth.uid();
  insert into public.admin_activity_log(admin_id,action,target_type,target_id,new_state) values(auth.uid(),'remote_config.set','config',p_key,p_value);
  return true;
end $$;

create or replace function public.cc_set_maintenance(p_enabled boolean,p_message text default null,p_starts_at timestamptz default null,p_ends_at timestamptz default null)
returns boolean language plpgsql security definer set search_path = public
as $$ begin
  if not public.cc_is_admin('admin') then raise exception 'not authorized'; end if;
  insert into public.maintenance_controls(id,enabled,message,starts_at,ends_at,updated_at) values(true,p_enabled,p_message,p_starts_at,p_ends_at,now())
  on conflict(id) do update set enabled=excluded.enabled,message=excluded.message,starts_at=excluded.starts_at,ends_at=excluded.ends_at,updated_at=now();
  return true;
end $$;

-- Client-safe RPCs. They expose only the current user's control data.
create or replace function public.myplan_register_device(
  p_installation_id text,p_user_id uuid,p_device_name text,p_manufacturer text,p_model text,
  p_android_version text,p_app_version text,p_fcm_token text default null
) returns boolean language plpgsql security definer set search_path = public
as $$ begin
  insert into public.devices(installation_id,user_id,device_name,manufacturer,model,android_version,app_version,fcm_token,last_seen_at)
  values(p_installation_id,p_user_id,p_device_name,p_manufacturer,p_model,p_android_version,p_app_version,p_fcm_token,now())
  on conflict(installation_id) do update set user_id=excluded.user_id,device_name=excluded.device_name,manufacturer=excluded.manufacturer,model=excluded.model,android_version=excluded.android_version,app_version=excluded.app_version,fcm_token=coalesce(excluded.fcm_token,public.devices.fcm_token),last_seen_at=now();
  return true;
end $$;

create or replace function public.myplan_log_security_event(p_installation_id text,p_user_id uuid,p_event_type text,p_severity text,p_details jsonb default '{}'::jsonb)
returns boolean language plpgsql security definer set search_path = public
as $$ begin
  insert into public.security_events(installation_id,user_id,event_type,severity,app_version,android_version,details)
  values(p_installation_id,p_user_id,p_event_type,p_severity,null,null,p_details); return true;
end $$;

-- RLS baseline. Control Center uses Auth; Android reads only data explicitly exposed by policies/RPCs.
alter table public.app_users enable row level security;
alter table public.devices enable row level security;
alter table public.premium_grants enable row level security;
alter table public.remote_config enable row level security;
alter table public.feature_flags enable row level security;
alter table public.app_versions enable row level security;
alter table public.remote_messages enable row level security;
alter table public.message_receipts enable row level security;
alter table public.support_conversations enable row level security;
alter table public.support_messages enable row level security;
alter table public.notification_jobs enable row level security;
alter table public.ad_settings enable row level security;
alter table public.maintenance_controls enable row level security;
alter table public.error_logs enable row level security;
alter table public.analytics_events enable row level security;
alter table public.admin_activity_log enable row level security;
alter table public.admins enable row level security;
alter table public.content_items enable row level security;
alter table public.target_groups enable row level security;
alter table public.target_group_members enable row level security;
alter table public.security_events enable row level security;

-- Admin full access policies.
drop policy if exists cc_admin_app_users on public.app_users;
create policy cc_admin_app_users on public.app_users for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_devices on public.devices;
create policy cc_admin_devices on public.devices for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_premium on public.premium_grants;
create policy cc_admin_premium on public.premium_grants for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_config on public.remote_config;
create policy cc_admin_config on public.remote_config for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_flags on public.feature_flags;
create policy cc_admin_flags on public.feature_flags for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_versions on public.app_versions;
create policy cc_admin_versions on public.app_versions for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_messages on public.remote_messages;
create policy cc_admin_messages on public.remote_messages for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_receipts on public.message_receipts;
create policy cc_admin_receipts on public.message_receipts for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_jobs on public.notification_jobs;
create policy cc_admin_jobs on public.notification_jobs for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_ads on public.ad_settings;
create policy cc_admin_ads on public.ad_settings for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_maintenance on public.maintenance_controls;
create policy cc_admin_maintenance on public.maintenance_controls for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_errors on public.error_logs;
create policy cc_admin_errors on public.error_logs for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_analytics on public.analytics_events;
create policy cc_admin_analytics on public.analytics_events for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_logs on public.admin_activity_log;
create policy cc_admin_logs on public.admin_activity_log for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_admins on public.admins;
create policy cc_admin_admins on public.admins for all using (public.cc_is_admin('owner')) with check (public.cc_is_admin('owner'));
drop policy if exists cc_admin_content on public.content_items;
create policy cc_admin_content on public.content_items for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_groups on public.target_groups;
create policy cc_admin_groups on public.target_groups for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_group_members on public.target_group_members;
create policy cc_admin_group_members on public.target_group_members for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_security on public.security_events;
create policy cc_admin_security on public.security_events for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));

-- Public client read policies are intentionally limited to operational content.
drop policy if exists client_read_active_config on public.remote_config;
create policy client_read_active_config on public.remote_config for select using (enabled = true);
drop policy if exists client_read_active_flags on public.feature_flags;
create policy client_read_active_flags on public.feature_flags for select using (enabled = true);
drop policy if exists client_read_active_versions on public.app_versions;
create policy client_read_active_versions on public.app_versions for select using (enabled = true);
drop policy if exists client_read_active_messages on public.remote_messages;
create policy client_read_active_messages on public.remote_messages for select using (is_active = true);
drop policy if exists client_read_maintenance on public.maintenance_controls;
create policy client_read_maintenance on public.maintenance_controls for select using (true);
drop policy if exists client_read_ads on public.ad_settings;
create policy client_read_ads on public.ad_settings for select using (true);

drop policy if exists cc_admin_support_conversations on public.support_conversations;
create policy cc_admin_support_conversations on public.support_conversations for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));
drop policy if exists cc_admin_support_messages on public.support_messages;
create policy cc_admin_support_messages on public.support_messages for all using (public.cc_is_admin('admin')) with check (public.cc_is_admin('admin'));

-- Client RPCs for real two-way support chat. They identify the client by installation_id
-- and only expose that installation's own conversation.
create or replace function public.myplan_send_support_message(
  p_installation_id text, p_user_id uuid, p_body text
) returns bigint language plpgsql security definer set search_path = public
as $$
declare v_conversation uuid; v_id bigint;
begin
  if coalesce(trim(p_body),'') = '' then raise exception 'empty message'; end if;
  select id into v_conversation from public.support_conversations
    where installation_id=p_installation_id and status='open'
    order by updated_at desc limit 1;
  if v_conversation is null then
    insert into public.support_conversations(user_id,installation_id) values(p_user_id,p_installation_id)
    returning id into v_conversation;
  else
    update public.support_conversations set user_id=coalesce(p_user_id,user_id),updated_at=now(),last_message_at=now()
      where id=v_conversation;
  end if;
  insert into public.support_messages(conversation_id,sender_type,sender_user_id,body,delivered_at)
    values(v_conversation,'user',p_user_id,p_body,now()) returning id into v_id;
  update public.support_conversations set updated_at=now(),last_message_at=now() where id=v_conversation;
  return v_id;
end $$;

create or replace function public.myplan_get_support_messages(
  p_installation_id text
) returns setof public.support_messages
language sql security definer set search_path = public
as $$
  select sm.* from public.support_messages sm
  join public.support_conversations sc on sc.id=sm.conversation_id
  where sc.installation_id=p_installation_id
  order by sm.created_at asc
  limit 200;
$$;

create or replace function public.myplan_mark_support_read(
  p_installation_id text
) returns integer language plpgsql security definer set search_path = public
as $$
declare n integer;
begin
  update public.support_messages sm set read_at=coalesce(read_at,now())
  from public.support_conversations sc
  where sc.id=sm.conversation_id and sc.installation_id=p_installation_id
    and sm.sender_type='admin' and sm.read_at is null;
  get diagnostics n = row_count;
  return n;
end $$;

