org.gradle.jvmargs=-Xmx700m -XX:MaxMetaspaceSize=200m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=false
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
systemProp.file.encoding=UTF-8
